Add options to send generic TLVs in the backend
sap-contributions/haproxy pull request #2
Opened 2023-08-08 13:26 UTC by alexanderstephan

**General TODOs**:
- [x] Fix a bug where a TLV value falls into a different pool, problem with freeing
- [x] Revise test
- [x] Split up commits: Maybe conn_set_tlv first and then the backend stuff, see https://github.com/sap-contributions/haproxy/tree/local-patch
- [x] Remove debug output
- [x] Add docs to ` configuration.txt`

2023-09-07 17:03 UTC, alexanderstephan commented on include/haproxy/connection.h
> +			if (tlv->type == type) {
```suggestion
			if (tlv->type != type) {
			     continue;
			  ...
```

2023-09-08 12:27 UTC, Garfield96 requested changes

2023-09-08 12:27 UTC, Garfield96 commented on src/server.c
> +			new_tlv = malloc(sizeof(struct srv_tlv_list));
```suggestion
			new_tlv = malloc(sizeof(struct srv_tlv_list));
			if (!new_tlv)
				goto fail;
```

2023-09-08 12:27 UTC, Garfield96 commented on src/tcp_act.c
> +		tlv_id = strtoul(cmd_name, &error, 0); /* convert TLV ID */
If there are no valid digits, 0 is returned and `errno` is set to `EINVAL`. However, currently, it would be considered as valid input.

2023-09-08 12:27 UTC, Garfield96 commented on src/connection.c
> +				ret += make_tlv(&buf[ret], (buf_len - ret), srv_tlv->type, replace->data, replace->area);
```suggestion
			if (&srv_tlv->list == &srv->pp_tlvs)
				continue;

			if (!LIST_ISEMPTY(&srv_tlv->fmt)) {
			        replace = alloc_trash_chunk();
			        if (!replace)
				    return 0;
				replace->data = build_logline(strm, replace->area, replace->size, &srv_tlv->fmt);
			}
			if (replace && replace->data > 0) {
				if ((buf_len - ret) < sizeof(struct tlv)) {
				        free_trash_chunk(replace)
					return 0;
			        }
				ret += make_tlv(&buf[ret], (buf_len - ret), srv_tlv->type, replace->data, replace->area);
				free_trash_chunk(replace)
```

2023-09-08 12:37 UTC, alexanderstephan commented on include/haproxy/connection.h
> +	if (!conn || !conn_ctrl_ready(conn) || (conn->flags & CO_FL_FDLESS) || len > HA_PP2_MAX_ALLOC)
Hm, wouldn't `conn` be `true` here?

2023-09-08 12:40 UTC, alexanderstephan commented on include/haproxy/connection.h
> +				else if (tlv->len > HA_PP2_TLV_VALUE_256 && len > HA_PP2_TLV_VALUE_256)
While I find this a bit harder to read, it removes some code duplication, so let's go for it. 👍

2023-09-13 12:06 UTC, Garfield96 commented on reg-tests/connection/proxy_protocol_send_generic.vtc
> +        http-after-response set-header proxy_custom_tlv_c %[var(txn.custom_tlv_c)]
Can we extend the test cases with invalid TLV types?

2023-09-13 12:06 UTC, Garfield96 commented on reg-tests/connection/proxy_protocol_send_generic.vtc
> +        http-request set-var(txn.custom_tlv_c) fc_pp_tlv(0343)
Octal is not mentioned in Docs.

2023-09-13 12:08 UTC, Garfield96 commented on src/connection.c
> +		struct buffer *replace = NULL;
```suggestion
		struct buffer *replace;
```

2023-09-13 12:12 UTC, Garfield96 commented on src/server.c
> +	free(srv_tlv);
`errno` should be reset.

2025-08-22 10:31 UTC, alexanderstephan commented
Commit in https://github.com/haproxy/haproxy/commit/ce7501de79b035a03c52aa47c671aac2fcdfd631.

2025-08-22 10:31 UTC, closed without merging